"""`tool-pouch init` — autodetect tools, provider, and model; write .tool_pouch.toml.

Designed to take the user from `pip install tool-pouch` to a working
`.tool_pouch.toml` in one command, with zero questions in the common case.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


CONFIG_FILENAME = ".tool_pouch.toml"

# Where users typically keep their tool functions, in priority order.
TOOL_PATH_CANDIDATES = [
    "tools.py",
    "tools/",
    "agent/tools.py",
    "agent/tools/",
    "src/tools.py",
    "src/tools/",
    "app/tools.py",
    "app/tools/",
]

DEFAULT_MODELS = {
    "openai": "gpt-4o-mini",
    "anthropic": "claude-opus-4-7",
}


@dataclass
class InitPlan:
    tools_path: Optional[str]
    provider: str
    model: str

    def as_toml(self) -> str:
        lines = [
            "# tool-pouch configuration — generated by `tool-pouch init`.",
            "# Run `tool-pouch scan` (no args) and these settings will be used.",
            "",
            "[tool-pouch]",
        ]
        if self.tools_path:
            lines.append(f'tools = "{self.tools_path}"')
        else:
            lines.append('# tools = "./your_tools/"   # set this once you decorate functions with @tool_pouch.tool')
        lines.append(f'provider = "{self.provider}"')
        lines.append(f'model = "{self.model}"')
        lines.append("")
        lines.append("# Optional — tool-pouch generates these from your tool docstrings if omitted.")
        lines.append('# test_inputs = ["best pizza in NYC"]')
        lines.append("")
        return "\n".join(lines)


def detect_tools_path(root: Path) -> Optional[str]:
    """Return the first matching tools location, or None."""
    for candidate in TOOL_PATH_CANDIDATES:
        p = root / candidate
        if p.exists():
            return f"./{candidate}"
    return None


def detect_provider() -> str:
    """Pick provider based on which API key is present.

    Both keys present: prefer OpenAI (more popular ecosystem).
    Neither: default to OpenAI so the file is still useful — they'll get a
    clear error when they actually run, with a hint to set the key.
    """
    has_openai = bool(os.environ.get("OPENAI_API_KEY"))
    has_anthropic = bool(os.environ.get("ANTHROPIC_API_KEY"))
    if has_openai:
        return "openai"
    if has_anthropic:
        return "anthropic"
    return "openai"


def make_plan(root: Path) -> InitPlan:
    provider = detect_provider()
    return InitPlan(
        tools_path=detect_tools_path(root),
        provider=provider,
        model=DEFAULT_MODELS[provider],
    )


def write(root: Path, plan: InitPlan, force: bool = False) -> Path:
    """Write the plan to .tool_pouch.toml in `root`. Returns the path written."""
    target = root / CONFIG_FILENAME
    if target.exists() and not force:
        raise FileExistsError(f"{target} already exists; pass --force to overwrite")
    target.write_text(plan.as_toml())
    return target
